---
# tasks file for Database
-
#  name: "Create File"
#  hosts: web1
#  gather_facts: no
#  vars:
#    count: 3
#  tasks:
- name: "Creating File on database Server"
  command: touch "{{ destination_directory }}/{{ database_filename }}{{ item }}.txt"
  loop: "{{ range(1, count + 1) | list }}"
