---
# # Example: Use of Ansible File or Module Include
- name: "Play1 : Create Files"
  hosts: web1
  become: true
  tasks:
    - name: Include variables
      ansible.builtin.include_vars:
        file: /root/Ansible_Course/variables.yaml

    - name: Create files
      ansible.builtin.file:
        path: "{{ destination_directory }}/{{ item.name }}"
        state: touch
      with_items : "{{ file_list }}"

    - name: Write content to files
      ansible.builtin.copy:
        content: "{{ item.content }}"
        dest: "{{ destination_directory }}/{{ item.name }}"
      with_items: "{{ file_list }}"
