---
- name: "Play1 : Create Files"
  hosts: web1
  become: true

  tasks:
    - name: Include variables
      ansible.builtin.include_vars:
        file: /root/Ansible_Course/variables.yaml
    
    - name: Debug destination_directory
      ansible.builtin.debug:
        var: destination_directory

    - name: Debug file_list
      ansible.builtin.debug:
        var: file_list

    - name: Create files
      ansible.builtin.file:
        path: "{{ destination_directory }}/{{ item.name }}"
        state: touch
      with_items : "{{ file_list }}"

    - name: Write content to files
      ansible.builtin.copy:
        content: "{{ item.content }}"
        dest: "{{ destination_directory }}/{{ item.name }}"
      with_items: "{{ file_list }}"
